import dotenv from 'dotenv';

dotenv.config();

const {
    MYSQL_HOST,
    MYSQL_USER,
    MYSQL_PASSWORD,
    MYSQL_DATABASE,
    PORT,
    JWT_SECRET,
    JWT_EXPIRATION,
    VITE_URL_FRONT,
    UPLOADS_DIR,
    SMTP_HOST,
    SMTP_PORT,
    SMTP_USER,
    SMTP_PASS,
    URL_FRONT,
    MongooseURL,
    STRIPE_PUB_KEY,
    STRIPE_PUB_TEST,
    STRIPE_SECRET_TEST,
    STRIPE_SECRET_KEY
} = process.env;

export {
    MYSQL_HOST,
    MYSQL_USER,
    MYSQL_PASSWORD,
    MYSQL_DATABASE,
    PORT,
    JWT_SECRET,
    JWT_EXPIRATION,
    UPLOADS_DIR,
    SMTP_HOST,
    SMTP_PORT,
    SMTP_USER,
    SMTP_PASS,
    MongooseURL,
    STRIPE_PUB_KEY,
    VITE_URL_FRONT,
    STRIPE_SECRET_KEY,
    STRIPE_PUB_TEST,
    STRIPE_SECRET_TEST,
    URL_FRONT,
};
